[package]
name = "profiler-get-symbols"
version = "0.1.0"
authors = ["Markus Stange <mstange@themasta.com>"]
license = "MIT/Apache-2.0"

[dependencies]
pdb = { git = "https://github.com/mcnulty/pdb/", branch="procedure-symbol" }
scroll = "0.9.2"
uuid = "0.5.1"
wasm-bindgen = "0.2"

[dependencies.object]
version = "0.10.0"
default-features = false
features = ["std"]

[dependencies.goblin]
# The version and features of goblin need to match what's in object's Cargo.toml,
# because we really want object's goblin and not another instance of goblin.
version = "0.0.17"
features = ["endian_fd", "elf32", "elf64", "mach32", "mach64", "pe32", "pe64", "archive"]
default-features = false

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
